package pojos;
// Generated Aug 15, 2019 11:25:08 PM by Hibernate Tools 4.3.1

/**
 * Score generated by hbm2java
 */
public class Score implements java.io.Serializable {

    private Integer scoreId;
    private float scoreMid;
    private float scoreLast;
    private float scoreOther;
    private float scoreAvg;
    private String studentId;
    private String fullName;
    private String subjectId;
    private String class_;

    public Score() {
    }

    public Score(float scoreMid, float scoreLast, float scoreOther, float scoreAvg, String studentId, String fullName, String subjectId, String class_) {
        this.scoreMid = scoreMid;
        this.scoreLast = scoreLast;
        this.scoreOther = scoreOther;
        this.scoreAvg = scoreAvg;
        this.studentId = studentId;
        this.fullName = fullName;
        this.subjectId = subjectId;
        this.class_ = class_;
    }

    public Integer getScoreId() {
        return this.scoreId;
    }

    public void setScoreId(Integer scoreId) {
        this.scoreId = scoreId;
    }

    public float getScoreMid() {
        return this.scoreMid;
    }

    public void setScoreMid(float scoreMid) {
        this.scoreMid = scoreMid;
    }

    public float getScoreLast() {
        return this.scoreLast;
    }

    public void setScoreLast(float scoreLast) {
        this.scoreLast = scoreLast;
    }

    public float getScoreOther() {
        return this.scoreOther;
    }

    public void setScoreOther(float scoreOther) {
        this.scoreOther = scoreOther;
    }

    public float getScoreAvg() {
        return this.scoreAvg;
    }

    public void setScoreAvg(float scoreAvg) {
        this.scoreAvg = scoreAvg;
    }

    public String getStudentId() {
        return this.studentId;
    }

    public void setStudentId(String studentId) {
        this.studentId = studentId;
    }

    public String getFullName() {
        return this.fullName;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    public String getSubjectId() {
        return this.subjectId;
    }

    public void setSubjectId(String subjectId) {
        this.subjectId = subjectId;
    }

    public String getClass_() {
        return this.class_;
    }

    public void setClass_(String class_) {
        this.class_ = class_;
    }
}
