package pojos;
// Generated Aug 7, 2019 11:50:32 PM by Hibernate Tools 4.3.1



/**
 * Score generated by hbm2java
 */
public class Score  implements java.io.Serializable {


     private Integer scoreId;
     private String studentCode;
     private float scoreMid;
     private float scoreLast;
     private float scoreOther;
     private float scoreAvg;
     private int studentId;

    public Score() {
    }

    public Score(String studentCode, float scoreMid, float scoreLast, float scoreOther, float scoreAvg, int studentId) {
       this.studentCode = studentCode;
       this.scoreMid = scoreMid;
       this.scoreLast = scoreLast;
       this.scoreOther = scoreOther;
       this.scoreAvg = scoreAvg;
       this.studentId = studentId;
    }
   
    public Integer getScoreId() {
        return this.scoreId;
    }
    
    public void setScoreId(Integer scoreId) {
        this.scoreId = scoreId;
    }
    public String getStudentCode() {
        return this.studentCode;
    }
    
    public void setStudentCode(String studentCode) {
        this.studentCode = studentCode;
    }
    public float getScoreMid() {
        return this.scoreMid;
    }
    
    public void setScoreMid(float scoreMid) {
        this.scoreMid = scoreMid;
    }
    public float getScoreLast() {
        return this.scoreLast;
    }
    
    public void setScoreLast(float scoreLast) {
        this.scoreLast = scoreLast;
    }
    public float getScoreOther() {
        return this.scoreOther;
    }
    
    public void setScoreOther(float scoreOther) {
        this.scoreOther = scoreOther;
    }
    public float getScoreAvg() {
        return this.scoreAvg;
    }
    
    public void setScoreAvg(float scoreAvg) {
        this.scoreAvg = scoreAvg;
    }
    public int getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(int studentId) {
        this.studentId = studentId;
    }




}


